/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fusesource_leveldbjni_internal_ChunkHelper */

#ifndef _Included_org_fusesource_leveldbjni_internal_ChunkHelper
#define _Included_org_fusesource_leveldbjni_internal_ChunkHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fusesource_leveldbjni_internal_ChunkHelper
 * Method:    nextChunk
 * Signature: (JJ)[[[B
 */
JNIEXPORT jobjectArray JNICALL Java_org_fusesource_leveldbjni_internal_ChunkHelper_nextChunk
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
