/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fusesource_leveldbjni_internal_ChunkHelper_Chunk */

#ifndef _Included_org_fusesource_leveldbjni_internal_ChunkHelper_Chunk
#define _Included_org_fusesource_leveldbjni_internal_ChunkHelper_Chunk
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
